### ISSUE TITLE
Add "feature-branches"

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/java-demo-client#3]
Add 3 feature branches:

feature-branch-1
feature-branch-2
feature-branch-3

Have `feature-branch-3` in a failed status.

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/77997420-abba6c80-732f-11ea-9c1c-cd95a67d5f6d.png)

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/78014613-7b32fc80-7348-11ea-89b6-4892c921527b.png)
