### ISSUE TITLE
Make Master green

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/java-demo-client#4]

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/77997458-bd037900-732f-11ea-97fb-97474a77d558.png)

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/78014643-84bc6480-7348-11ea-9bad-b7ff789db724.png)
