### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/java-demo-client#5]
README should contain instructions on how to clone this project and how to run it locally with Scope for Mac/Windows to obtain Scratchpad results.

Ideally, all integration tests are automatically configured to be ran against our "production" hamburguesía instance, such that when I run them locally I still the full traces in Scratchpad.

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/78014689-943bad80-7348-11ea-88d6-1c1214339cee.png)
